### ISSUE TITLE
[MedtrumKit] Couple of small problems

### ISSUE THREAD

**Issue by LiroyvH** [nightscout/Trio#758]
## Describe the bug
Using this issue to describe a few problems (-edit- ✅ = resolved):

✅ 1.) When using a MD0xxx pumpbase (not sure if the same goes for MD8xxx as Medtrum still hasn't delivered them to me), under Insulin Pump the pump identifies as "Medtrum TouchCare Nano UNKNOWN". I suspect this may be because it can only differentiate the 8xxx models; but was just a theory. It does see it in pump status.

WONTFIX 2.) IAGE and CAGE are not updated in Nightscout. When switching from Medtronic to Medtrum, these values remain populated in Nightscout. It would be nice if at the very least these values are cleared out (but that might be Trio generic rather than MedtrumKit generic now I think of it), but I'd sooner like to propose that IAGE/CAGE are updated with the patch runtime (which *is* Medtrum specific :P)
-edit- This problem will not be fixed in MedtrumKit but should allegedly be solved if #682 gets merged. (Requires re-test)

✅ 3.) The remaining units in the reservoir are being uploaded to Nightscout in enormous fractions. Eg, at the moment of writing this I'm seeing "189.60000000000005U" remaining.

✅ 4.) The pump state that is being uploaded to Nightscout is stuck at "bolusing". 

Finally, just piggybacking this one as someone (@10nas) on Discord pointed it out as well and I saw the same:
✅ 5.) The priming process on the Medtrum takes an eternity. It'd be nice if the screen stays awake whilst it's doing that. The risk is that the app is suspended/terminated when it backgrounds whilst the phone is locked, which may lead to losing the patch. Warning the user not to close the app would be a good addition too. 

## Attach a Log
Logs are available on request.

## To Reproduce
Use Medtrum + Nightscout. There are no specific steps to trigger these conditions.

## Expected behavior
- The "UNKNOWN" should probably be a 200U or 300U distinction
- IAGE/CAGE should be updated with the pump start time or otherwise be cleared out on first time use
- Remaining units sent to nightscout should be rounded down to the nearest integer (imho)
- Pump state should be accurate or cleared out 
- Screen should stay awake until priming is complete and "Activate patch" has been tapped. And warn user not to close the app/keep app in foreground without locking phone. 

## Screenshots

<img width="1206" height="2622" alt="Image" src="https://github.com/user-attachments/assets/4a4b8cdd-21e9-403c-a1fb-56448d537b51" />

![Image](https://github.com/user-attachments/assets/d176e251-90e7-4b73-87b0-8b4386edecdf)

### Smartphone:
iPhone 16 Pro running latest iOS 18

### Pump:
Medtrum Nano 200U MD02xx

### CGM:
Dexcom G6

### Trio Version:
0.5.1.20 (1), repo: nightscout/trio, branch: feat/dev-medtrum
(Note: synced to latest version available in that branch. Looks like it is slightly behind) 

## Technical Details
NaN

## Additional context
NaN

**Comment by bastiaanv** [comment]
@LiroyvH 

- Item 1, could you share the SN of your pump base? Then I can check why you get the 
- Item 2: I've updated the MedtrumKit driver to emit `type: .replaceComponent(componentType: .pump)`. I am not sure if it updates IAGE & CAGE. It is the same event emitted by OmniBLE
- Item 3: Should be fixed
- Item 4: Need to check this, interesting problem
- Item 5: Should be fixed

The Medtrum SHA for all the fixes: [15c5686](https://github.com/loopandlearn/MedtrumKit/tree/dev)
https://github.com/jbr7rr/MedtrumKit/pull/16

**Comment by LiroyvH** [comment]
@bastiaanv Thanks! I'll try building it again tomorrow :) (very much maybe late tonight). I've sent you a DM with the serial number.

**Comment by MikePlante1** [comment]
> * Item 2: I've updated the MedtrumKit driver to emit `type: .replaceComponent(componentType: .pump)`. I am not sure if it updates IAGE & CAGE. It is the same event emitted by OmniBLE


Ah, that explains it. This should be resolved when #682 gets merged, then.

**Comment by bastiaanv** [comment]
- Item 1: issue has been fixed
- Item 4: I think the issue has been fixed, but needs validation @LiroyvH 

The Medtrum SHA for all the fixes: [2e7939e](https://github.com/loopandlearn/MedtrumKit/tree/dev)

**Comment by LiroyvH** [comment]
Hi @bastiaanv,

To go through the whole list: 
- Item 1 is fixed, looks good.
- Item 2 does not appear to be fixed, BUT I will double-check if it by any chance updates it during the next patch change
- Item 3 appears to be fixed
- Item 4 appears to be fixed, I saw it alternate between "normal" and "bolusing" when relevant. Will keep an eye on it.
- Item 5 I will re-check on next patch change

Thank you for the updates! :)

**Comment by LiroyvH** [comment]
@bastiaanv 
Update: I'd consider 5 partially fixed. It stays awake during priming, but falls asleep when waiting for the user to finish putting it on their body and tap "activate patch". The same issue may occur then. 

Also, can confirm point 2 isn't fixed. IAGE and CAGE aren't being updated.

**Comment by bastiaanv** [comment]
@LiroyvH Could you update to https://github.com/loopandlearn/MedtrumKit/commit/ed1e81aeee3d7c251ce8f43f750f47a81c7b76c0?

Item 2 will be fixed with #682 like @MikePlante1 said.
Maybe pull that PR manual, if you want to test?

**Comment by LiroyvH** [comment]
@bastiaanv Ahhh then I misunderstood. I thought you fixed it by adding the trigger and I didn't see #682 referencing the Medtrum. But then I will just wait for that to be merged, manually doing things with git is an absolute clustercopulation - so I'll steer clear of that. 

I'm building ed1e81a as we speak. :)

**Comment by LiroyvH** [comment]
@bastiaanv 
Item 5 I can confirm is fixed :) If item 2 will be fixed by Mike's PR then all items appear to be fixed - just require, imho, at least one other person to test/verify. From my pov: these look fixed.

**Comment by bastiaanv** [comment]
This issue can be closed once #766 is merged

**Comment by LiroyvH** [comment]
@bastiaanv Small thing on this one, when you tap the start priming button - at first seemingly nothing happens. It takes a few seconds to get the priming process started, at which point it starts showing the spinning circle and grays out the buttons. I'm not sure if it would be problematic, but this *might* get users to tap the "start priming" button multiple times as they may think they didn't tap it/it didn't register. It might be nice if that can be improved, though strictly speaking not part of the earlier mentioned problems. (Just part of the same "keep screen awake" portion). 

Strangely, whilst just starting the priming process: the app did not keep the screen awake. I'm not sure how that's possible as it was working before. (I did use MDT for a few days in between) I'll double check my build, pretty sure I didn't downgrade it.
