### ISSUE TITLE
[alpha-issue] - TidePool - Looks like all boluses are labeled as "automated". This highlighted bolus was manual.

### ISSUE THREAD

**Issue by avouspierre** [nightscout/Trio#77]
Looks like all boluses are labeled as "automated". This highlighted bolus was manual.

(This test was done via the alpha branch, not specifically this PR, btw)

<img width="280" alt="Tidepool Manual Bolus" src="https://github.com/nightscout/Open-iAPS/assets/82073483/e564f4b4-3cfb-4bc0-aea6-d9de7d746e17">

_Originally posted by @MikePlante1 in https://github.com/nightscout/Open-iAPS/issues/30#issuecomment-2045816305_

**Comment by bjornoleh** [comment]
I think this is resolved, but maybe not by the PR that was referenced above.

**Comment by marionbarker** [comment]
This is not resolved. I just tested it. All boluses are labeled automatic:
* smb
* manual bolus
* external bolus

In Loop the distinction is made that manual and external (non-pump) both show up as manual (no label shown and a lighter blue) and automatic shows up as automatic (label says automatic and darker blue).

**Comment by marionbarker** [comment]
This issue is still present in main branch.

**Comment by dnzxy** [comment]
Addressed for TCD / Trio 1.0.0 dev.

**Comment by dnzxy** [comment]
Closing as this was addressed in upcoming public beta 0.5.0
